#!/usr/bin/env php
<?php

/**
 * Simply require console entry point, framework will take care of things.
 */
try {
    require_once "vendor/pckg/framework/src/console.php";
} catch (Exception $e) {
    dd(exception($e));
}
