#!/usr/bin/env bash
# this script should be loaded from https://impero.foobar.si/installer/[userhash]

# @REMOTE

# set variables
# password should be randomly generated by remote using some function
# user should be 'impero', if not set differently
# hash should be set on our side, unique and one per user so we can
$IMPEROPASSWORD = 'iMp3R0p4SsW0rD' # @T00D00 - ask user for password or / and randomly generate password
$IMPEROUSER = 'impero' # @T00D00 - ask for impero username
$IMPEROHASH = 'r4Nd0MlYg3N3r4T3dH4sH' # @T00D00 - both, generate and store this on impero side
$USERHASH = 'r4Nd0MuS3rH4sH' # @T00D00 - generate this on impero side
$HASHEDPASSWORD = 'iMp3R0p4SsW0rDimperor4Nd0MlYg3N3r4T3dH4sH', # @T00D00 - use two-way algorithm, using $IMPEROHASH ?

# add impero user, do not create home directory, set password, do not request name, room and phone
# openssl passwd -crypt myPassword
echo 'Creating user'
adduser $IMPEROUSER -M -p $IMPEROPASSWORD --gecos

# add user to sudo group
echo 'Adding user to sudo group'
usermod -aG sudo $IMPEROUSER

# change sudoers file
echo 'Adding user to sudoers'
echo '# User rules for impero' >> /etc/sudoers.d/100-impero
echo 'impero ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/100-impero

# notify supervisor and create server
echo 'Notifying supervisor about new server, this can take a moment ...'
curl -X POST https://impero.foobar.si/api/installer/new-server/[userhash]?hostname=$HOSTNAME&password=$HASHEDPASSWORD&user=$IMPEROUSER

# @T00D00 - set $REMOTEID variable

# @SUPERVISOR

# supervisor will catch request and resolve password
# this shouldn't take more than 5 seconds
# generate rsa key, 4096bit, without password
# @T00D00 - use password, it's stronger!
echo 'Generating rsa key'
ssh-keygen -b 4096 -t rsa -C 'impero@remote' -f /tmp/impero_remote -N ""

# transfer it to remote
echo 'Transfering rsa key'
echo 'Checking connection'
sshpass -p $IMPEROPASSWORD ssh-copy-id -p 22 $IMPEROUSER@remote

# try to connect
echo 'Checking connection'
ssh impero@remote

# @REMOTE

# during supervisor actions, we need to wait on remote.
# @T00D00 - wait for info, make request each 5 seconds
echo 'Waiting for supervisor to estamblish connection ...'
curl -X POST https://impero.foobar.si/api/installer/check-init/[userhash]/$REMOTEID/$IMPEROHASH

# change password and / or disable login with password
# change ssh config
# PermitRootLogin no / without-password

# notify user
echo "Connection successfully estamblished. You can check status in impero panel."